/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const MedicalKit = (props) => {
  const { nodes, materials } = useGLTF('/models-3d/medkit_01.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Medkit_1.geometry}
        material={materials.White}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Medkit_2.geometry}
        material={materials.DarkGrey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Medkit_3.geometry}
        material={materials.Grey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Medkit_4.geometry}
        material={materials.Red}
      />
    </group>
  )
}

export default MedicalKit

useGLTF.preload('/models-3d/medkit_01.glb')